### ISSUE TITLE
No proper labels shown

### ISSUE THREAD

**Issue by Shurtu-gal** [jatin69/codechef-contest-calendar#3]
Only busy is being shown instead of competitions' names.
See the screenshot.
<img width="959" alt="Screenshot 2022-07-03 232120" src="https://user-images.githubusercontent.com/100484401/177051513-010f2c2b-2754-4a52-ab66-82b9bb96c987.png">

**Comment by jatin69** [comment]
Hi @Shurtu-gal 

The screenshot seems to be from official codechef website. I have no affiliation with the calendar on the official site. 
Although, i am able to see proper names on the [official calendar](https://www.codechef.com/event-calendar?itm_medium=navmenu&itm_campaign=calendar)
 

The repo you created an issue in was a custom calendar made by parsing the contests page. It was made at the time because the official calendar on the website was broken. Also, I haven't really maintained it in the last 2 years. The cron job was also disabled about 2 years ago.

Closing this issue since it's about the official calendar.
